use_frameworks!

target 'TJTestPod_Example' do
  pod 'TJTestPod', :path => '../'

  target 'TJTestPod_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
